test_that("Wrapper function of gathering results works", {
  data("datasetA")
  eg <- gatherResults(log2(datasetA$prot))
  expect_type(eg, "list")
  expect_equal(length(eg), 6)
  expect_type(eg[[1]], "list")
  expect_type(eg[[2]], "list")
  expect_type(eg[[3]], "list")
  expect_type(eg[[4]], "list")
  expect_type(eg[[5]], "list")
  expect_type(eg[[6]], "list")
  expect_length(eg[[1]], 7)
  expect_length(eg[[2]], 3)
  expect_length(eg[[3]], 3)
  expect_identical(dim(eg[[4]]), c(4L, 4L))
  expect_length(eg[[5]], 2)
  expect_length(eg[[6]], 11)
})
