#' Dataset A: Hybrid proteome data
#'
#' Hybrid proteome samples were generated by mixing human, yeast and E.coli
#' lysates in different ratios and analysed by SWATH-MS. The dataset of
#' interest was obtained from TripleTOF6600 with the 64-variable-window
#' acquisition. The dataset was processed by DIA-NN under the library-based
#' mode. Only triplicates of Sample A are included here.
#'
#' @docType data
#'
#' @format List of data matrices of precursor- and protein-level intensities.
#'
#' @references
#' Navarro, P., Kuharev, J., Gillet, L.C., Bernhardt, O.M., MacLean, B., Röst,
#' H.L., Tate, S.A., Tsou, C.C., Reiter, L., Distler, U. and Rosenberger, G.,
#' 2016. A multicenter study benchmarks software tools for label-free proteome
#' quantification. \emph{Nature biotechnology}, 34(11), pp.1130-1136.
#'
#' Demichev, V., Messner, C.B., Vernardis, S.I., Lilley, K.S. and Ralser, M.,
#' 2020. DIA-NN: neural networks and interference correction enable deep
#' proteome coverage in high throughput. \emph{Nature methods}, 17(1), pp.41-44.
"datasetA"

#' Dataset B: Single cell proteomes
#'
#' Four cell populations enriched in different cell cycle stages were produced
#' from HeLa cells by drug treatment. MS data were obtained by the diaPASEF
#' mode and analysed by DIA-NN in library-based mode.
#'
#' @docType data
#'
#' @format List of data matrices of precursor- and protein-level intensities.
#'
#' @references
#' Brunner, A.D., Thielert, M., Vasilopoulou, C., Ammar, C., Coscia, F., Mund,
#' A., Hoerning, O.B., Bache, N., Apalategui, A., Lubeck, M. and Richter, S.,
#' 2022. Ultra‐high sensitivity mass spectrometry quantifies single‐cell
#' proteome changes upon perturbation. \emph{Molecular systems biology},
#' 18(3), p.e10798.
"datasetB"






#' Dataset C: HepG2 technical replicate data
#'
#' Technical replicates of HepG2 cell lysates were acquired in DIA mode and
#' analysed by MaxDIA in discovery mode.
#'
#' @docType data
#'
#' @format List of data matrices of precursor- and protein-level intensities.
#'
#' @references
#' Sinitcyn, P., Hamzeiy, H., Salinas Soto, F., Itzhak, D., McCarthy, F.,
#' Wichmann, C., Steger, M., Ohmayer, U., Distler, U., Kaspar-Schoenefeld, S.
#' and Prianichnikov, N., 2021. MaxDIA enables library-based and library-free
#' data-independent acquisition proteomics. \emph{Nature biotechnology}, 39(12),
#' pp.1563-1573
"datasetC"





#' Dataset D: Human blood plasma proteome
#'
#' MS data were acquired for human blood plasma samples from acute inflammation
#' patients in DDA mode. Raw MS data were then analysed by MaxQuant.
#'
#' @docType data
#'
#' @format List of data matrices of precursor- and protein-level intensities.
#'
#' @references
#' Prianichnikov, N., Koch, H., Koch, S., Lubeck, M., Heilig, R., Brehmer, S.,
#' Fischer, R. and Cox, J., 2020. MaxQuant software for ion mobility enhanced
#' shotgun proteomics. \emph{Molecular & Cellular Proteomics}, 19(6),
#' pp.1058-1069.
"datasetD"




#' Supplementary Dataset: Sydney Heart Bank data
#'
#' Cryopreserved left ventricular myocardium samples from the human hearts were
#' analysed. MS data were acquired in DIA mode and analysed by Spectronaunt v12
#' with a DDA spectral library generated from the pooled sample.
#'
#' @docType data
#'
#' @format List of data matrices of precursor- and protein-level intensities.
#'
#' @references
#' Li, M., Parker, B.L., Pearson, E., Hunter, B., Cao, J., Koay, Y.C.,
#' Guneratne, O., James, D.E., Yang, J., Lal, S. and O’Sullivan, J.F., 2020.
#' Core functional nodes and sex-specific pathways in human ischaemic and
#' dilated cardiomyopathy. \emph{Nature communications}, 11(1), pp.1-12.
#'
"shbheart"


#' Supplementary Dataset : UPS1 spiked in yeast extract
#'
#' Three concentrations of UPS1 (25 fmol, 10 fmol and 5 fmol) were spiked in
#' yeast extract. This is a DDA dataset processed by MaxQuant. Here we use the
#' dataset which compares 25 fmol to 10 fmol spiked-ins.
#'
#' @docType data
#'
#' @format List of data matrices of precursor- and protein-level intensities.
#'
#' @references
#' Gianetto, Q.G., Combes, F., Ramus, C., Bruley, C., Couté, Y. and Burger, T.,
#' 2016. Calibration plot for proteomics: A graphical tool to visually check the
#' assumptions underlying FDR control in quantitative experiments.
#' \emph{Proteomics}, 16(1), pp.29-32.
#'
"ratio2.5"

